/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //tests.testCase01();
        //END Tests
        //tests.endTest(); // End your test by clearning connections and closing browser

        //TODO: call your test case functions one after other here

        //AmazonSearch()
        // AmazonSearch tests = new AmazonSearch();
        // tests.searchAmazon();
        // tests.endTest();

        //BookMyShow
        //   BookMyShow tests = new BookMyShow();
        // tests.hyperLink();
        //   tests.recommendedMovies();
        //   tests.endTest();

        //LinkedIn
        // LinkedIn tests = new LinkedIn();
        // tests.createPost();
        // tests.postImage();
        // tests.endTest();

       // NestedFrames
           NestedFrames tests = new NestedFrames();
           tests.nestedFrames();
           tests.endTest();

        // IMDB Ratings
        // IMDBRatings tests = new IMDBRatings();
        // tests.ratings();
        // tests.endTest();

        //WindowHandles
        // WindowHandles tests = new WindowHandles();
        // tests.windowHandles();
        // tests.endTest();

 
    
        
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
